spring:
  application:
    name: config-server-module
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: file:../ms-config-files
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/