spring:
  application:
    name: config-server-module
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/my-spring-boot-workspace/banking-microservice-sb/ms-config-files
server:
  port: 8080